### PR TITLE
Knn support functions

### LINKED ISSUE #14: knn_utils.h should be moved to dimensionality_reduction project
knn_utils.h which contains enumerated types for KNN algorithms and KNN algorithm distance measures is currently in the utils project. However, the utils project has no information (e.g. defines) regarding supported KNN algorithms. This is currently all handled in the dimensionality_reduction project.

Moving knn_utils.h from the utils project to the dimensionality reduction project would make it a lot easier to add functions which return which KNN algorithm is supported and which distance measure is supported for which KNN algorithm.

It would be possible to add these functions in the dimensionality_reduction project but this leads to information regarding KNN algorithms to be split over several projects.

### PR DESCRIPTION
**Pull request by jeggermont**
Moved knn_utils from utils to dimensionality reduction and added some convenience functions to get supported knn-libraries and supported distance measures for a specific knn library. Changed the default for using roaring to OFF instead of ON. Also optimized the getAreaOfInfluence in dimensionality_reduction/hierarchical_sne

### CODE REVIEW

**Review by bldrvnlw — APPROVED** [review]
Great the latest CMake FindOpenMP is brew aware.

**Review by bldrvnlw — CHANGES_REQUESTED** [review]
Could you add some comments to this new set of utils? In general the HDILib project is comment poor, it would be nice to change that. What is missing is not the 'how it works' (the code is clear enough) but the 'why is it needed'. For example " To allow configuration and discover of knn metrics, and ? " .

**Comment by bldrvnlw** [comment]
For future reference: it's probably a good idea to rebase the individual development commits (of which there are often many) to a smaller and clearer number of final commits before the pull. It makes the review process simpler. Personally I use Atlassian Sourcetree the rebase (it's in the right click menu called "Rebase children of <sha> interactively") as I find the GUI there less error prone but it also works from the command line.

**Review by bldrvnlw — COMMENTED** [review]
Why does std::unordered_set<unsigned_int_type> set_selected_idxes(selection.cbegin(), selection.cend()) move inside the parallel for?

**Comment by bldrvnlw** [comment]
My biggest problem is following the changes to getAreaOfInfluence although they are actually not so large. Other than the omp change to schedule dynamic I find it difficult to say if there is a bug in the new version of the algorithm or not. The problem is not your changes but the fact that this piece of code is already pretty terse and lacking in description. I'm sure you have some clear insight as to how it works now. Would it be possible to add a few lines of comment and if possible indicate the corresponding section in  https://doi.org/10.1111/cgf.12878 (section 3.3?)?

**Comment by jeggermont** [comment]
splitting this pull request up into 3 separate requests.

**Pull request closed without merging**
